-- DROP TABLE IF EXISTS uid_generator.WORKER_NODE;
CREATE TABLE `WORKER_NODE`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'auto increment id',
    `HOST_NAME` VARCHAR(64) NOT NULL COMMENT 'host name',
    `PORT` VARCHAR(64) NOT NULL COMMENT 'port',
    `TYPE` INT NOT NULL COMMENT 'node type: ACTUAL or CONTAINER',
    `LAUNCH_DATE` DATE NOT NULL COMMENT 'launch date',
    `MODIFIED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'modified time',
    `CREATED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
    PRIMARY KEY(`ID`)
) ENGINE = INNODB;
